services:
  glpi:
    image: diouxx/glpi:latest
    container_name: glpi
    ports:
      - "8080:80"
    volumes:
      - glpi_data:/var/www/html
      - ./local_plugins:/var/www/html/glpi/plugins
      - ./local_plugins:/var/www/html/glpi/marketplace
    environment:
      - GLPI_DB_HOST=db
      - GLPI_DB_NAME=glpi
      - GLPI_DB_USER=glpi
      - GLPI_DB_PASS=glpi
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: glpi_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    volumes:
      - db_data:/var/lib/mysql

volumes:
  glpi_data:
  db_data:
